services:
  e-comm-art:
    container_name: e-comm-art
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
